spring:
  datasource:
    url: jdbc:mysql://localhost:3306/winemakers
    username: root
    password: admin
  liquibase:
    contexts: prod
  web:
    resources:
      static-locations: classpath:/static/,file:///C:/Users/Public/MySQL-Files
app:
  storage:
    location: /Users/Public/MySQL-Files