spring:
  datasource:
    url: jdbc:h2:mem:test
  liquibase:
    contexts: dev
  jpa:
    hibernate:
      ddl-auto: validate
  web:
    resources:
      static-locations: classpath:/static/,file:./uploads/
app:
  storage:
    location: ./uploads/