spring:
  datasource:
    url: jdbc:h2:mem:test
  liquibase:
    contexts: dev
    change-log: classpath:db/changelog/master.xml
  web:
    resources:
      static-locations: classpath:/static/,file:./uploads/
  jpa:
    hibernate:
      ddl-auto: validate
app:
  storage:
    location: ./uploads/